pipelines:
  - name: check
    description: Newly uploaded patchsets enter this pipeline to receive an initial +/-1 Verified vote from Jenkins.
    success-message: Build succeeded.
    failure-message: Build failed.
    manager: IndependentPipelineManager
    source: gerrit
    precedence: normal
    require:
      open: True
      current-patchset: True
    trigger:
      gerrit:
        - event: patchset-created
        - event: change-restored
        - event: comment-added
          comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*(recheck compassci)
        - event: comment-added
          require-approval:
            - verified: [-1, -2]
            - username: compass-ci
          approval:
            - workflow: 1
    success:
      gerrit:
        verified: 1
    failure:
      gerrit:
        verified: -1

  - name: tests
    manager: IndependentPipelineManager
    trigger:
      gerrit:
        - event: patchset-created
          email_filter: ^.*@example.org$
    success:
      gerrit:
        verified: 1
    failure:
      gerrit:
        verified: -1

  - name: post
    manager: IndependentPipelineManager
    trigger:
      gerrit:
        - event: ref-updated
          ref: ^(?!refs/).*$

  - name: gate
    manager: DependentPipelineManager
    trigger:
      gerrit:
        - event: comment-added
          approval:
            - approved: 1
    start:
      gerrit:
        verified: 0
    success:
      gerrit:
        verified: 1
    failure:
      gerrit:
        verified: -1

jobs:
  - name: compass-demo
    branch: master
    voting: true

  - name: compass-bare-e2e-allin1
    branch: master
    voting: false

  - name: compass-bare-e2e-single-controller-allin1
    branch: master
    voting: false

  - name: compass-bare-e2e-multinodes-allin1
    branch: master
    voting: false

  - name: compass-bare-e2e-single-contoller-multi-compute
    branch: master
    voting: false

  - name: compass-bare-e2e-osonly
    branch: master
    voting: false

  - name: compass-bare-e2e-allin1-ubuntu
    branch: master
    voting: false

  - name: compass-bare-e2e-single-contoller-multi-compute-ubuntu
    branch: master
    voting: false

projects:
  - name: stackforge/compass-core
    check:
      - compass-demo
      - compass-bare-e2e-allin1
      - compass-bare-e2e-single-controller-allin1
      - compass-bare-e2e-single-contoller-multi-compute
      - compass-bare-e2e-osonly
      - compass-bare-e2e-allin1-ubuntu
      - compass-bare-e2e-single-contoller-multi-compute-ubuntu

  - name: stackforge/compass-adapters
    check:
      - compass-demo
      - compass-bare-e2e-allin1
      - compass-bare-e2e-single-controller-allin1
      - compass-bare-e2e-single-contoller-multi-compute
      - compass-bare-e2e-osonly
      - compass-bare-e2e-allin1-ubuntu
      - compass-bare-e2e-single-contoller-multi-compute-ubuntu
