---
- name: restart controller relation service
  service: name={{ item }} state=restarted enabled=yes
  ignore_errors: True
  with_items: controller_services

- name: restart compute relation service
  service: name={{ item }} state=restarted enabled=yes
  ignore_errors: True
  with_items: compute_services
