---
packages:
  - nova-api
  - nova-cert
  - nova-conductor
  - nova-consoleauth
  - nova-novncproxy
  - nova-scheduler
  - python-oslo.rootwrap

services:
  - nova-api
  - nova-cert
  - nova-conductor
  - nova-consoleauth
  - nova-novncproxy
  - nova-scheduler
