# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "compass"
  config.vm.network :private_network, ip: "192.168.33.10"
  config.vm.provider :virtualbox do |vb|
    vb.memory = 2048
  end

  config.vm.provision "shell", path: "enable-nat.sh"
  config.vm.synced_folder "machines/", "/etc/compass/machine_list"
  config.vm.synced_folder "compass-adapters/ansible/openstack_juno", "/var/ansible/openstack_juno"
  config.vm.synced_folder "compass-adapters/ansible/openstack_juno_plumgrid", "/var/ansible/openstack_juno_plumgrid"
end
