---
- include_vars: "{{ ansible_os_family }}.yml"

- name: Install ODL Cluster on Controller
  include: odl_controller.yml
  when: inventory_hostname in groups['odl']

- name: Install ODL Cluster on Compute
  include: openvswitch.yml
  when: groups['odl']|length !=0 and inventory_hostname not in groups['odl']
