---
- name: Install XORP to provide IGMP router functionality
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=present"
  with_items: xorp_packages

- name: create xorp directory
  file: path=/etc/xorp state=directory

- name: configure xorp
  template: src=etc/xorp/config.boot dest=/etc/xorp/config.boot
  notify:
    - restart xorp

- name: set xorp defaults
  copy: src=xorp dest=/etc/default/xorp
  notify:
    - restart xorp

- meta: flush_handlers

- name: start and enable xorp service
  service: name=xorp state=started enabled=yes
  retries: 2
  delay: 10
