---

- hosts: cobblernodes
  sudo: True
  roles:
    - { role: cobbler }

- hosts: chefnodes
  sudo: True
  roles:
    - { role: chef }

- hosts: compassnodes
  sudo: True
  roles:
    - { role: compass }
