---
- name: install glance packages
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=latest"
  with_items: packages | union(packages_noarch)

- name: generate glance service list
  shell: echo {{ item }} >> /opt/service
  with_items: services | union(services_noarch)

- name: update glance conf
  template: src={{ item }} dest=/etc/glance/{{ item }}
            backup=yes
  with_items:
    - glance-api.conf
    - glance-registry.conf

- name: remove default sqlite db
  shell: rm /var/lib/glance/glance.sqlite || touch glance.sqllite.db.removed
