---

- hosts: regtest_vm
  sudo: True
  roles:
    - regtest-compass
#    - regtest-ansible-openstack
  vars:
    - COMPASS_PATH: "/opt/compass-core"
    - COMPASS_SERVER_URL: "http://10.1.0.11:5000/api"
    - COMPASS_USER_EMAIL: "admin@huawei.com"
    - COMPASS_USER_PASSWORD: "admin"
    - CLUSTER_NAME: "opnfv"
    - LANGUAGE: "EN"
    - TIMEZONE: "America/Los_Angeles"
    - HOSTNAMES: "allinone"
    - NTP_SERVER: "10.1.0.11"
    - NAMESERVERS: "10.1.0.11"
    - DOMAIN: "ods.com"
    - PARTITIONS: "/home=5%,/tmp=5%,/var=20%"
    - SUBNETS: "10.1.0.0/24,172.16.2.0/24,172.16.3.0/24,172.16.4.0/24"
    - ADAPTER_OS_PATTERN: '"(?i)ubuntu-14\.04.*"'
    - ADAPTER_NAME: "os_only"
    - ADAPTER_TARGET_SYSTEM_PATTERN: ""
    - ADAPTER_FLAVOR_PATTERN: ""
    - PROXY: ""
    - IGNORE_PROXY: ""
    - SEARCH_PATH: "ods.com"
    - GATEWAY: "10.1.0.1"
    - SERVER_CREDENTIAL: "root"
    - LOCAL_REPO_URL: ""
    - OS_CONFIG_FILENAME: ""
    - SERVICE_CREDENTIALS: "service"
    - CONSOLE_CREDENTIALS: "console"
    - HOST_NETWORKS: "allinone:eth0=10.1.0.100|is_mgmt,eth1=172.16.2.100,eth2=172.16.3.100,eth3=172.16.4.100"
    - NETWORK_MAPPING: "management=eth0,tenant=eth1,storage=eth3,external=eth2"
    - PACKAGE_CONFIG_FILENAME: ""
    - HOST_ROLES: ""
    - DEFAULT_ROLES: ""
    - SWITCH_IPS: "1.1.1.1"
    - MACHINES: ""
    - SWITCH_CREDENTIAL: "version=2c,community=public"
    - DEPLOYMENT_TIMEOUT: "90"
    - POLL_SWITCHES_FLAG: "nopoll_switches"
    - DASHBOARD_URL: ""
