
TYPE: baremetal
FLAVOR: cluster
POWER_TOOL: ipmitool

ipmiUser: root
ipmiVer: '2.0'

hosts:
  - name: host2
    mac: 'E0:24:7F:02:15:A3'
    ipmiIp: 172.16.130.28
    ipmiPass: huawei@123
    roles:
      - controller
      - ha

  - name: host3
    mac: 'D8:49:0B:DA:2A:28'
    ipmiIp: 172.16.130.29
    ipmiPass: Huawei@123
    roles:
      - controller
      - ha

  - name: host4
    mac: 'D8:49:0B:DA:5B:5D'
    ipmiIp: 172.16.130.30
    ipmiPass: Huawei@123
    roles:
      - compute

  - name: host5
    mac: 'D8:49:0B:DA:56:85'
    ipmiIp: 172.16.130.31
    ipmiPass: Huawei@123
    roles:
      - compute

